### PR TITLE
Support uuids as pks on roda actions

### PR DESCRIPTION
**Pull request by badosu**
Fix default action urls for when the primary key of a model includes dashes

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch! The patch looks good, can you please add a spec for it?

**Comment by badosu** [comment]
@jeremyevans Done! I had to perform a small change on `db_setup` for it to allow custom primary keys

**Comment by jeremyevans** [comment]
Looks good, I'll test and merge shortly.

**Comment by badosu** [comment]
Thanks!

**Pull request merged**
